### ISSUE TITLE
Automate merging with upstream

### ISSUE THREAD

**Issue by RobotsOnDrugs** [HardenedBSD/hardenedbsd-doc#1]
-doc needs to be kept up-to-date like the main HBSD repos.

**Comment by RobotsOnDrugs** [comment]
@opntr can you provide some information on your bot and how you use it for the main source repo?

**Comment by opntr** [comment]
yup, I will setup them, you can find the scripts in tools.git git repo

**Comment by opntr** [comment]
done.
